name: MapleTesting Build
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build CDI
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/kos-container
        with:
          run: |
            source /opt/toolchains/dc/kos/environ.sh
            make elf
            make cdi

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: MapleTest
          path: |
            build/mapletest.elf
            build/mapletest.cdi

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     prerelease: true
      #     tag_name: latest_build
      #     files: |
      #       build/mapletest.cdi
      #       build/mapletest.elf

      # - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "ğŸ This job's status is ${{ job.status }}."
